-- Таблицы ooofix-xmlupd-cloud в существующей БД btops_app
-- (CREATE DATABASE не выполняется — база уже создана хостингом)
--
-- mysql -u btops_app -p btops_app < database/install_btops_app.sql

CREATE TABLE IF NOT EXISTS portals (
    ID            INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DOMAIN        VARCHAR(255) NOT NULL,
    MEMBER_ID     VARCHAR(64) DEFAULT NULL,
    ACCESS_TOKEN  TEXT,
    REFRESH_TOKEN TEXT,
    EXPIRES_AT    DATETIME DEFAULT NULL,
    INSTALLED_AT  DATETIME NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UX_PORTAL_DOMAIN (DOMAIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS portal_settings (
    PORTAL_ID   INT UNSIGNED NOT NULL,
    OPTION_KEY  VARCHAR(64) NOT NULL,
    OPTION_VALUE TEXT,
    PRIMARY KEY (PORTAL_ID, OPTION_KEY),
    CONSTRAINT FK_SETTINGS_PORTAL FOREIGN KEY (PORTAL_ID) REFERENCES portals (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b_xmldoc_log (
    ID          INT NOT NULL AUTO_INCREMENT,
    PORTAL_ID   INT UNSIGNED NOT NULL,
    REQUEST_ID  VARCHAR(36) DEFAULT NULL,
    ENTITY_TYPE VARCHAR(32) NOT NULL,
    ENTITY_ID   INT NOT NULL,
    STATUS      VARCHAR(32) NOT NULL,
    MESSAGE     TEXT,
    CREATED_AT  DATETIME NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_LOG_PORTAL (PORTAL_ID),
    KEY IX_LOG_REQUEST (REQUEST_ID),
    KEY IX_LOG_ENTITY (ENTITY_TYPE, ENTITY_ID),
    KEY IX_LOG_CREATED (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b_xmldoc_document (
    ID                 INT NOT NULL AUTO_INCREMENT,
    PORTAL_ID          INT UNSIGNED NOT NULL,
    ENTITY_TYPE        VARCHAR(32) NOT NULL,
    ENTITY_ID          INT NOT NULL,
    DOC_NUMBER         VARCHAR(64) DEFAULT NULL,
    FILE_NAME          VARCHAR(255) NOT NULL,
    FILE_ID            INT DEFAULT NULL,
    VERSION            INT NOT NULL DEFAULT 1,
    ENCODING           VARCHAR(16) DEFAULT 'windows-1251',
    FILE_HASH          VARCHAR(64) DEFAULT NULL,
    DOC_STATUS         VARCHAR(32) NOT NULL DEFAULT 'generated',
    XML_FORMAT_VERSION VARCHAR(8) DEFAULT '5.03',
    CREATED_AT         DATETIME NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_DOC_PORTAL (PORTAL_ID),
    KEY IX_DOC_ENTITY (ENTITY_TYPE, ENTITY_ID),
    KEY IX_DOC_VERSION (ENTITY_TYPE, ENTITY_ID, VERSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS queue_jobs (
    ID           INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PORTAL_ID    INT UNSIGNED NOT NULL,
    REQUEST_ID   VARCHAR(36) DEFAULT NULL,
    ENTITY_TYPE  VARCHAR(32) NOT NULL,
    ENTITY_ID    INT NOT NULL,
    USER_ID      INT UNSIGNED NOT NULL DEFAULT 0,
    EVENT_TOKEN  TEXT,
    SOURCE       VARCHAR(32) NOT NULL DEFAULT 'robot',
    STATUS       VARCHAR(16) NOT NULL DEFAULT 'pending',
    PAYLOAD      JSON DEFAULT NULL,
    RESULT       JSON DEFAULT NULL,
    ERROR_TEXT   TEXT,
    ATTEMPTS     TINYINT UNSIGNED NOT NULL DEFAULT 0,
    CREATED_AT   DATETIME NOT NULL,
    STARTED_AT   DATETIME DEFAULT NULL,
    FINISHED_AT  DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    KEY IX_QUEUE_PORTAL_STATUS (PORTAL_ID, STATUS),
    KEY IX_QUEUE_CREATED (CREATED_AT),
    CONSTRAINT FK_QUEUE_PORTAL FOREIGN KEY (PORTAL_ID) REFERENCES portals (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
