-- Миграция production (MySQL 5.7+)
-- mysql -u root -p dbname < database/migrations/001_production.sql
-- Примечание: SchemaMigrator применяет эти изменения автоматически при первом подключении к БД.

ALTER TABLE b_xmldoc_log ADD COLUMN REQUEST_ID VARCHAR(36) DEFAULT NULL AFTER PORTAL_ID;
ALTER TABLE b_xmldoc_log ADD KEY IX_LOG_REQUEST (REQUEST_ID);

ALTER TABLE queue_jobs ADD COLUMN REQUEST_ID VARCHAR(36) DEFAULT NULL AFTER PORTAL_ID;

CREATE TABLE IF NOT EXISTS queue_jobs (
    ID           INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PORTAL_ID    INT UNSIGNED NOT NULL,
    REQUEST_ID   VARCHAR(36) DEFAULT NULL,
    ENTITY_TYPE  VARCHAR(32) NOT NULL,
    ENTITY_ID    INT NOT NULL,
    USER_ID      INT UNSIGNED NOT NULL DEFAULT 0,
    EVENT_TOKEN  TEXT,
    SOURCE       VARCHAR(32) NOT NULL DEFAULT 'robot',
    STATUS       VARCHAR(16) NOT NULL DEFAULT 'pending',
    PAYLOAD      JSON DEFAULT NULL,
    RESULT       JSON DEFAULT NULL,
    ERROR_TEXT   TEXT,
    ATTEMPTS     TINYINT UNSIGNED NOT NULL DEFAULT 0,
    CREATED_AT   DATETIME NOT NULL,
    STARTED_AT   DATETIME DEFAULT NULL,
    FINISHED_AT  DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    KEY IX_QUEUE_PORTAL_STATUS (PORTAL_ID, STATUS),
    KEY IX_QUEUE_CREATED (CREATED_AT),
    CONSTRAINT FK_QUEUE_PORTAL FOREIGN KEY (PORTAL_ID) REFERENCES portals (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
