-- Миграция: недостающие колонки queue_jobs / b_xmldoc_log (MySQL 5.7+)
-- mysql -u USER -p DB < database/migrations/002_schema_columns.sql
-- Примечание: SchemaMigrator применяет это автоматически при подключении к БД.

ALTER TABLE queue_jobs ADD COLUMN REQUEST_ID VARCHAR(36) DEFAULT NULL AFTER PORTAL_ID;
ALTER TABLE queue_jobs ADD COLUMN ENTITY_TYPE VARCHAR(32) NOT NULL DEFAULT 'deal' AFTER REQUEST_ID;
ALTER TABLE queue_jobs ADD COLUMN ENTITY_ID INT NOT NULL DEFAULT 0 AFTER ENTITY_TYPE;
ALTER TABLE queue_jobs ADD COLUMN USER_ID INT UNSIGNED NOT NULL DEFAULT 0 AFTER ENTITY_ID;
ALTER TABLE queue_jobs ADD COLUMN EVENT_TOKEN TEXT AFTER USER_ID;
ALTER TABLE queue_jobs ADD COLUMN SOURCE VARCHAR(32) NOT NULL DEFAULT 'robot' AFTER EVENT_TOKEN;
ALTER TABLE queue_jobs ADD COLUMN STATUS VARCHAR(16) NOT NULL DEFAULT 'pending' AFTER SOURCE;
ALTER TABLE queue_jobs ADD COLUMN PAYLOAD JSON DEFAULT NULL AFTER STATUS;
ALTER TABLE queue_jobs ADD COLUMN RESULT JSON DEFAULT NULL AFTER PAYLOAD;
ALTER TABLE queue_jobs ADD COLUMN ERROR_TEXT TEXT AFTER RESULT;
ALTER TABLE queue_jobs ADD COLUMN ATTEMPTS TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER ERROR_TEXT;
ALTER TABLE queue_jobs ADD COLUMN CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER ATTEMPTS;
ALTER TABLE queue_jobs ADD COLUMN STARTED_AT DATETIME DEFAULT NULL AFTER CREATED_AT;
ALTER TABLE queue_jobs ADD COLUMN FINISHED_AT DATETIME DEFAULT NULL AFTER STARTED_AT;

ALTER TABLE b_xmldoc_log ADD COLUMN PORTAL_ID INT UNSIGNED NOT NULL DEFAULT 0 AFTER ID;
ALTER TABLE b_xmldoc_log ADD COLUMN REQUEST_ID VARCHAR(36) DEFAULT NULL AFTER PORTAL_ID;

ALTER TABLE b_xmldoc_document ADD COLUMN PORTAL_ID INT UNSIGNED NOT NULL DEFAULT 0 AFTER ID;
